# TINVOICES
#TINVOICES_SELECT_LAST_NUMBER = SELECT MAX(number) FROM TInvoices
#TINVOICES_INSERT = INSERT INTO TInvoices \
#                   (id, number, date, vat, amount, state, version, \
#                   createdAt, updatedAt, entityState) \
#                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TINVOICES_FINDNEXTNUMBER = select max(number) \
                           from TInvoices
TINVOICES_ADD = insert into TInvoices \
                (id, version, number, date, state, subtotal, total, \
                vatRate, vatAmount, createdAt, updatedAt, entityState) \
                values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

# TMECHANICS
TMECHANICS_ADD = insert into TMechanics(id, nif, name, surname, version, \
                 createdAt, updatedAt, entityState) \
                 values (?, ?, ?, ?, ?, ?, ?, ?)
TMECHANICS_DELETE = delete from TMechanics where id = ?
TMECHANICS_FINDBYID = select id, nif, name, surname, version, \
                      createdAt, updatedAt, entityState \
                      from TMechanics \
                      where id = ?
TMECHANICS_FINDBYNIF = select id, nif, name, surname, version, \
                       createdAt, updatedAt, entityState \
                       from TMechanics \
                       where nif = ?
TMECHANICS_FINDALL = select id, nif, name, surname, version, \
                     createdAt, updatedAt, entityState \
                     from TMechanics
TMECHANICS_UPDATE = update TMechanics \
                    set name = ?, surname = ?, nif = ?, \
                    version = version + 1, updatedat = ? \
                    where id = ?

# TWORKORDERS
#TWORKORDERS_FIND_NOT_INVOICED = select a.id, a.description, a.date, a.state, \
#                                a.amount from TWorkOrders as a, TVehicles as v, \
#                                TClients as c \
#                                where a.vehicle_id = v.id \
#                                and v.client_id = c.id \
#                                and state like 'APPROVED' \
#                                and nif like ?
#TWORKORDERS_UPDATE_VERSION = update TWorkOrders set version=version+1 where id = ?
#TWORKORDERS_FIND_ID_BY_ID = SELECT id FROM TWorkOrders WHERE id = ?
#TWORKORDERS_FIND_STATUS_BY_ID = SELECT state FROM TWorkOrders WHERE id = ?
#TWORKORDERS_FIND_AMOUNT_BY_ID = SELECT amount FROM TWorkOrders WHERE id = ?
#TWORKORDERS_UPDATE_INVOICEID = UPDATE TWorkOrders SET invoice_id = ? WHERE id = ?
#TWORKORDERS_UPDATE_STATE = UPDATE TWorkOrders SET state = 'INVOICED' WHERE id = ?
#TWORKORDERS_UPDATE_TIMESTAMP = UPDATE TWorkOrders SET updatedat = ? WHERE id = ?
TWORKORDERS_COUNT_BY_MECHANIC = select count(*) \
                                from TWorkOrders \
                                where mechanic_id = ?
TWORKORDERS_FINDAMOUNT = select total_amount \
                         from TWorkOrders \
                         where id = ?
TWORKORDERS_FINDID = select id \
                     from TWorkOrders \
                     where id = ?
TWORKORDERS_FINDSTATE = select state \
                        from TWorkOrders \
                        where id = ?
TWORKORDERS_UPDATEINVOICEID = update TWorkOrders \
                              set invoice_id = ? \
                              where id = ?
TWORKORDERS_UPDATESTATE = update TWorkOrders \
                          set state = 'INVOICED' \
                          where id = ?
TWORKORDERS_UPDATEVERSION = update TWorkOrders \
                            set version = version + 1 \
                            where id = ?
TWORKORDERS_UPDATETIMESTAMP = update TWorkOrders \
                              set updatedAt = ? \
                              where id = ?

# TINTERVENTIONS
TINTERVENTIONS_COUNT_BY_MECHANIC = select count(*) \
                                   from TInterventions \
                                   where mechanic_id = ?